# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 19:50
from __future__ import unicode_literals

import directory
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("places", "0002_auto_20151221_1217")]

    operations = [
        migrations.AlterField(
            model_name="office",
            name="phone_number",
            field=directory._localflav(blank=True, max_length=32),
        )
    ]
