# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 15:58
from __future__ import unicode_literals

import re

import directory
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0006_auto_20160126_1350")]

    operations = [
        migrations.AddField(
            model_name="person",
            name="sync_name",
            field=models.BooleanField(
                default=True,
                help_text=b"Synchronize name information with corresponding user model",
                verbose_name=b"sync name with user",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="username",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text=b"Username on the local system, if the person has one. 64 characters or fewer. Letters, numbers and @/./+/-/_ characters",
                max_length=64,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile(b"^[\\w.@+-]+$"),
                        b"Enter a valid username.",
                        b"invalid",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="number",
            field=directory._localflav(max_length=32),
        ),
        migrations.AlterField(
            model_name="streetaddress",
            name="postal_code",
            field=directory._localflav(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="streetaddress",
            name="region",
            field=directory._localflav(
                blank=True,
                help_text=b"Provinces in Canada, States for U.S.A.",
                max_length=64,
            ),
        ),
    ]
