# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 20:02
from __future__ import unicode_literals

import autoslug.fields
import directory
import people.conf
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("people", "0007_auto_20160317_1058")]

    operations = [
        migrations.AlterField(
            model_name="contactinfotype",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, max_length=32, populate_from=b"verbose_name_plural"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=False,
                help_text=b"A url fragment for this person, if required.",
                null=True,
                populate_from=people.conf.get("person:slug:populate_from"),
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="personflag",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                max_length=64,
                populate_from=b"verbose_name",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="number",
            field=directory._localflav(max_length=32),
        ),
        migrations.AlterField(
            model_name="streetaddress",
            name="postal_code",
            field=directory._localflav(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="streetaddress",
            name="region",
            field=directory._localflav(
                blank=True,
                help_text=b"Provinces in Canada, States for U.S.A.",
                max_length=64,
            ),
        ),
    ]
