# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 14:19
from __future__ import unicode_literals

import re

import autoslug.fields
import directory
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0009_auto_20170602_1100")]

    operations = [
        migrations.AlterField(
            model_name="contactinfotype",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, max_length=32, populate_from="verbose_name_plural"
            ),
        ),
        migrations.AlterField(
            model_name="emailaddress",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="emailaddress",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last modification time"
            ),
        ),
        migrations.AlterField(
            model_name="emailconfirmation",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="emailconfirmation",
            name="delete_unverified",
            field=models.BooleanField(
                default=False,
                help_text="If this is set, unverified email addresses and people objects will be deleted",
            ),
        ),
        migrations.AlterField(
            model_name="emailconfirmation",
            name="email_send_time",
            field=models.DateTimeField(
                help_text="If this is not set, the verification email has <em>not</em> been sent.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailconfirmation",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last modification time"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="birthday",
            field=models.DateField(
                blank=True,
                help_text="If this is not required, just leave this blank.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="cn",
            field=models.CharField(
                blank=True,
                help_text="This is how the person's name will appear in the site.\n                                    Leave this blank to use given name + family name.\n                                    ",
                max_length=100,
                verbose_name="common name",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="company",
            field=models.CharField(
                blank=True,
                help_text="The company this person if affiliated with.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="person",
            name="given_name",
            field=models.CharField(
                help_text="Typically how the person prefers to be addressed, informally.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last modification time"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=False,
                help_text="A url fragment for this person, if required.",
                null=True,
                populate_from="cn",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="sn",
            field=models.CharField(
                help_text="This will determine how this person gets sorted in lists or people.",
                max_length=64,
                verbose_name="family name",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="sync_name",
            field=models.BooleanField(
                default=True,
                help_text="Synchronize name information with corresponding user model",
                verbose_name="sync name with user",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="title",
            field=models.CharField(
                blank=True, help_text="A personal title or job title.", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="username",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Username on the local system, if the person has one. 64 characters or fewer. Letters, numbers and @/./+/-/_ characters",
                max_length=64,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[\\w.@+-]+$", 32),
                        "Enter a valid username.",
                        "invalid",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="personflag",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="personflag",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last modification time"
            ),
        ),
        migrations.AlterField(
            model_name="personflag",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, max_length=64, populate_from="verbose_name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last modification time"
            ),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="number",
            field=directory._localflav(max_length=32),
        ),
        migrations.AlterField(
            model_name="streetaddress",
            name="city",
            field=models.CharField(
                blank=True, help_text="(Township, Municipality, etc.)", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="streetaddress",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="streetaddress",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last modification time"
            ),
        ),
        migrations.AlterField(
            model_name="streetaddress",
            name="postal_code",
            field=directory._localflav(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="streetaddress",
            name="region",
            field=directory._localflav(
                blank=True,
                help_text="Provinces in Canada, States for U.S.A.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="streetaddress",
            name="street_2",
            field=models.CharField(blank=True, help_text="Optional", max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name="emailaddress", unique_together=set([("person", "address")])
        ),
    ]
