# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 20:15
from __future__ import unicode_literals

import directory
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("people", "0014_auto_20171011_1002")]

    operations = [
        migrations.AlterField(
            model_name="phonenumber",
            name="number",
            field=directory._localflav(max_length=32),
        ),
        migrations.AlterField(
            model_name="streetaddress",
            name="postal_code",
            field=directory._localflav(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="streetaddress",
            name="region",
            field=directory._localflav(
                blank=True,
                help_text="Provinces in Canada, States for U.S.A.",
                max_length=64,
            ),
        ),
    ]
