# Generated by Django 2.0 on 2017-12-06 20:49

import directory
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("people", "0015_auto_20171108_1415")]

    operations = [
        migrations.AlterField(
            model_name="phonenumber",
            name="number",
            field=directory.PhoneNumberField(max_length=128),
        ),
        migrations.AlterField(
            model_name="streetaddress",
            name="postal_code",
            field=directory.PostalCodeField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name="streetaddress",
            name="region",
            field=directory.RegionField(
                blank=True,
                help_text="Provinces in Canada, States for U.S.A.",
                max_length=64,
            ),
        ),
    ]
