# Generated by Django 2.2.2 on 2019-06-04 14:47

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("people", "0016_auto_20171206_1449")]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=False,
                null=True,
                populate_from="cn",
                unique=True,
                verbose_name="URL fragment",
            ),
        )
    ]
