# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-02 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("person_tags", "0002_auto_20150611_1109")]

    operations = [
        migrations.AlterModelOptions(
            name="persontag",
            options={"base_manager_name": "objects", "ordering": ["tag"]},
        ),
        migrations.AlterModelOptions(
            name="persontaggedentry",
            options={
                "base_manager_name": "objects",
                "ordering": ["person", "ordering", "tag"],
                "verbose_name_plural": "person tagged entries",
            },
        ),
        migrations.AlterModelOptions(
            name="taggroup",
            options={"base_manager_name": "objects", "ordering": ["name"]},
        ),
    ]
