# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("person_tags", "0003_auto_20170602_1101")]

    operations = [
        migrations.AddField(
            model_name="taggroup",
            name="short_name",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="persontag",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="persontag",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last modification time"
            ),
        ),
        migrations.AlterField(
            model_name="persontaggedentry",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="persontaggedentry",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last modification time"
            ),
        ),
        migrations.AlterField(
            model_name="taggroup",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="creation time"),
        ),
        migrations.AlterField(
            model_name="taggroup",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="last modification time"
            ),
        ),
        migrations.AlterField(
            model_name="taggroup", name="name", field=models.CharField(max_length=128)
        ),
        migrations.AlterField(
            model_name="taggroup",
            name="slug",
            field=models.SlugField(max_length=32, unique=True),
        ),
    ]
