# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("person_tags", "0004_auto_20170919_1150")]

    operations = [
        migrations.AlterField(
            model_name="persontag",
            name="tag",
            field=models.CharField(
                help_text="A word or short phrase (only a few words) is best.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="persontaggedentry",
            name="ordering",
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
