# Generated by Django 2.1.2 on 2018-11-30 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("person_tags", "0006_auto_20171012_1455")]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="creation time"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last modification time"
                    ),
                ),
                ("file", models.FileField(upload_to="person-tags/%Y/%m")),
                ("description", models.CharField(blank=True, max_length=250)),
                (
                    "taggroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="person_tags.TagGroup",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="persontaggedentry",
            name="person",
            field=models.ForeignKey(
                limit_choices_to={"active": True, "flags__slug": "directory"},
                on_delete=django.db.models.deletion.CASCADE,
                to="people.Person",
            ),
        ),
        migrations.AlterField(
            model_name="persontaggedentry",
            name="tag",
            field=models.ForeignKey(
                limit_choices_to={"active": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="person_tags.PersonTag",
            ),
        ),
    ]
