# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 19:50
from __future__ import unicode_literals

import directory
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("directory", "0004_auto_20151221_1217")]

    operations = [
        migrations.AlterField(
            model_name="directoryentry",
            name="phone_number",
            field=directory._localflav(
                blank=True,
                default=b"",
                help_text=b"(Optional) if not given, the office's phone number will be used.",
                max_length=32,
            ),
        )
    ]
